// This file is auto-generated by generate-scenes.js.
// Do not edit manually.

import type { SceneDefinition } from "../types/scenes";

// Chapter 01
import arrivalLawn from "./chapter01/arrival-lawn";
import backyardClothesline from "./chapter01/backyard-clothesline";
import carMirrorCheck from "./chapter01/car-mirror-check";
import porch from "./chapter01/porch";
import streetExit from "./chapter01/street-exit";

export type SceneId =
  | "arrival-lawn"
  | "backyard-clothesline"
  | "car-mirror-check"
  | "porch"
  | "street-exit"
;

export const scenes: SceneDefinition[] = [
  // Chapter 01
  arrivalLawn,
  backyardClothesline,
  carMirrorCheck,
  porch,
  streetExit,
];

export const initialSceneId: SceneId = "arrival-lawn";
